services:

    db:
        image: postgres
        volumes:
          - db-data:/var/lib/postgresql/data/
        ports:
          - 5436:5432
        restart: always
        environment:
          POSTGRES_PASSWORD: example

    redis:
        image: redis
        ports:
            - 6379:6379

volumes:
    db-data:
        driver: local